return {
  {
    "joryeugene/dadbod-grip.nvim",
    version = "*",
    cmd = {
      "Grip",
      "GripStart",
      "GripHome",
      "GripConnect",
      "GripSchema",
      "GripTables",
      "GripQuery",
      "GripSave",
      "GripLoad",
      "GripHistory",
      "GripProfile",
      "GripExplain",
      "GripAsk",
      "GripDiff",
      "GripCreate",
      "GripDrop",
      "GripRename",
      "GripProperties",
      "GripExport",
      "GripAttach",
      "GripDetach",
      "GripOpen",
    },
    keys = {
      { "<leader>db", "<cmd>GripConnect<cr>", desc = "DB connect" },
      { "<leader>dg", "<cmd>Grip<cr>", desc = "DB grid" },
      { "<leader>dt", "<cmd>GripTables<cr>", desc = "DB tables" },
      { "<leader>dq", "<cmd>GripQuery<cr>", desc = "DB query pad" },
      { "<leader>ds", "<cmd>GripSchema<cr>", desc = "DB schema" },
      { "<leader>dh", "<cmd>GripHistory<cr>", desc = "DB history" },
    },
    opts = {},
  },
}
